app/urls.py
from django.urls import path
from . import views # import all views in views file inside app(this) folder

app_name = 'app'

urlpatterns = [


    #url for home view in app views
    path('home/', views.home, name ='home'),


    #url for simple_render view in app views
    path('simple/', views.simple_render, name='simple'),


    #url for simple_render_with_context view in app views
    path('simple/context/', views.render_with_context, name='simple'),


    #url for simple_list view in app views
    path('simple/list/', views.simple_list, name='simple-list'),


    #url for simple_detail view in app views
    path('simple/detail/', views.simple_detail, name='simple-detail'),

    #url for store list view in app views
    path('list/', views.store_list, name='list'),


    #url for store detail view in app views containing store_slug of slug type
    path('detail/<slug:store_slug>', views.store_detail, name='detail'),


    #url for store create view in app views
    path('create/', views.store_create, name='create'),


    #url for store update view in app views containing store_slug of slug type
    path('update/<slug:store_slug>', views.store_update, name='update'),


	#url for store delete view in app views containing store_slug of slug type
    path('delete/<slug:store_slug>', views.store_delete, name='delete'),


    #url for signup view in app views
    path('signup/', views.signup, name='signup'),


    #url for signin view in app views
    path('signin/', views.signin, name='signin'),


    #url for signout view in app views
    path('signout/', views.signout, name='signout'),


    #url for item create view in app views containing store_slug of slug type
    path('create/item/store/<slug:store_slug>', views.item_create, name='item-create'),


    #url for item update view in app views containing item_slug of slug type
    path('update/item/<slug:item_slug>', views.item_update, name='item-update'),


    #url for store delete view in app views containing item_slug of slug type
    path('delete/item/<slug:item_slug>', views.item_delete, name='item-delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings           # import settings file to import static function
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    #namespace allows same url name in different apps
    # app_name variable should be defined in url file of app
    # namespace should be added before all urls
    path('app/', include('app.urls', namespace='app')),  
]

# += as it adds newly added files in static folder
# STATIC_URL defined in settings
# STATIC_ROOT defined in settings
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

'''
static folder is created inside app and contains: 
1) css style sheet(custom.css)
2) js style sheet(custom.js)
3) images (logos, background images and banners)
'''

app/templates/base.html
<!DOCTYPE html>
{% load static %}  <!-- load static folder-->

<html lang="en">
<head>

	<!-- static tag used to fetch custom css file and link it to base.html file -->
	<link rel="stylesheet" type="text/css" href="{%static 'custom.css'%}"> 

	<!-- bootstrap link overwrites custom.css file -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


	<meta charset="UTF-8">
	<title>{%block title%} {%endblock%}</title>
</head>
<body>

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<header> 

   
	{%include "navbar.html" %}

</header>
	<!-- good practice to wrap body in container in base file -->
	<!-- my-5 is margin at y-axis of 5, range (1-5) -->
	<div class="container my-5" >   
	{%block body%}{%endblock%}     
	</div>


	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/create.html
{%extends "base.html"%}
{% load crispy_forms_tags%} <!-- crispy forms loaded--> 
{%block title%} Create Store {%endblock%}


{%block body%}
	
	<div class = "jumbotron">   <!-- jumbotron form container-->
	<form method = "POST" action = "{% url 'app:create' %}" enctype="multipart/form-data">
	{%csrf_token%}
	{{form|crispy}}
	<input type="submit" value="Create Store">
	</form>
	</div>  <!-- end of jumbotron -->

{%endblock%}

app/templates/detail.html
{%extends "base.html"%}
{% load static %}


{%block title%}Simple Detail {%endblock%}


{%block body%}
	{%if store.image%}      <!-- if image available display it else display default image -->
		<img src={{store.image.url}} alt="store image">
	{%else%}
		<img src="{%static 'default.png'%}" alt="default image">
	{%endif%} 

		<ul>
			<li>Name: {{store.name|upper}}</li>   <!-- pipe used to insert django template filters -->
			<li>Location: {{store.location}}</li>
			<li>Description: {{store.description}}</li>
			<li>Cuisine: {{store.category}}</li>
		</ul>

		{%if request.user == store.owner%}    <!-- permission: display buttons for owner only -->
			<a href = "{%url 'app:update' store.slug%}" > <button> UPDATE </button> </a>
			<a href = "{%url 'app:delete' store.slug%}" > <button> DELETE </button> </a>
			<a href = "{%url 'app:item-create' store.slug%}" > <button> CREATE ITEM </button> </a>
		{%endif%}




	{%for item in store.items.all%}

	<div class="col-12 col-xl-3 col-lg-4 col-md-6"> <!-- start of column after for loop -->


	{%if item.image%}      <!-- if image available display it else display default image -->
		<img src={{item.image.url}} alt="item image">
	{%else%}
		<img src="{%static 'default.png'%}" alt="default image">
	{%endif%} 


	{%if request.user == store.owner%}    <!-- permission: display buttons for owner only -->
	<ul>
		<li>{{item.name}} -  {{item.price}} </li>
		<!-- price_range is a method if used in views or model obj.price_range() -->
		<li>{{item.price_range}}</li>  
		<a href = "{%url 'app:item-update' item.slug%}" > <button> UPDATE </button> </a>
		<a href = "{%url 'app:item-delete' item.slug%}" > <button> DELETE </button> </a>
	</ul>
	{%endif%}


	</div> <!-- end of column -->


	{%endfor%}

	</div> <!-- end of row -->
	




{%endblock%}

app/templates/item_create.html
{%extends "base.html"%}
{% load crispy_forms_tags%} <!-- crispy forms loaded--> 
{%block title%} Create Item {%endblock%}


{%block body%}
	
	<div class = "jumbotron">   <!-- jumbotron form container-->
	<form method = "POST" action = "{% url 'app:item-create' store.slug%}" enctype="multipart/form-data">
	{%csrf_token%}
	{{form|crispy}}
	<input type="submit" value="Create Item">
	</form>
	</div>  <!-- end of jumbotron -->

{%endblock%}

app/templates/item_update.html
{%extends "base.html"%}
{% load crispy_forms_tags%} <!-- crispy forms loaded--> 
{%block title%}Update Item {%endblock%}

{%block body%}

	<div class = "jumbotron">   <!-- jumbotron form container-->
		<form method = "POST" action = "{% url 'app:item-update' item.slug %}" enctype="multipart/form-data">
		{%csrf_token%}
		{{form|crispy}}
		<input type="submit" value="Update Item">
		</form>
	</div>                      <!-- end of jumbotron form -->

{%endblock%}

app/templates/list.html
{%extends "base.html"%}
{% load static %}       <!-- static should be loaded in sheet if used in it-->

{%block title%} Store List {%endblock%}

{%block body%}

	<!-- bootdtrap grid system consisting of rows and columns -->
	<div class="row">   <!-- start of row before for loop-->  

	{%for store in stores%}

	<div class="col-12 col-xl-3 col-lg-4 col-md-6"> <!-- start of column after for loop -->


	{%if store.image%}      <!-- if image available display it else display default image -->
		<img src={{store.image.url}} alt="store image">
	{%else%}
		<img src="{%static 'default.png'%}" alt="default image">
	{%endif%} 



	<ul>
		<!-- using absolute url to hyperlink store to its detail page -->
		<!-- cleaner as url name is only written in get_absolute_url function in Store model -->
		<li><a href = "{{store.get_absolute_url}}" >{{store.name}}</a> -  {{store.location}} </li>


		<!-- OR -->

		<!-- using url tag to hyperlink store to its detail page -->
		<!-- if url name changed in urls file it should be changed in all url tags -->
		<li><a href = "{%url 'app:detail' store.slug%}" >{{store.name}}</a> -  {{store.location}} </li>
		{%if request.user == store.owner%}    <!-- permission: display buttons for owner only -->
		<a href = "{%url 'app:update' store.slug%}" > <button> UPDATE </button> </a>
		<a href = "{%url 'app:delete' store.slug%}" > <button> DELETE </button> </a>
		{%endif%}
	</ul>

	</div> <!-- end of column -->

	{%endfor%}

	</div> <!-- end of row -->

{%endblock%}

app/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <!-- logo image fetched from static folder -->
  <a class="navbar-brand" href="{%url 'app:list'%}"><img src="{% static 'logo.png' %}" alt= "logo"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {%if request.user.is_anonymous%}
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'app:signin' %}">Signin <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'app:signup' %}">Signup</a>
      </li>
      {%endif%}

      {%if request.user.is_authenticated%}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'app:create' %}">Create Store</a>
      </li>
      {%endif%}

      <!--
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      -->

      {%if request.user.is_authenticated%}
      <li class="nav-item">
        <a class="nav-link disabled" tabindex="-1" aria-disabled="true">{{request.user}}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'app:signout' %}">Signout</a>
      </li>
      {%endif%}

    </ul>
    {% if request.path == "/list/" %}
    <form class="form-inline my-2 my-lg-0" action="{%url 'app:list'%}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name ='q' value='{{request.GET.q}}'>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    {%endif%}

  </div>
</nav>

app/templates/signin.html
{%extends 'base.html'%}
{% load crispy_forms_tags%} <!-- crispy forms loaded-->
{% block title %}
	Signin
{% endblock title %}

{% block body %}

	<div class = "jumbotron">   <!-- jumbotron form container-->
	<form method = "POST" action = "{% url 'app:signin' %}" enctype="multipart/form-data">
	{%csrf_token%}
	{{form|crispy}}
	<input type="submit" value="Signin">
	</form>
	</div>  <!-- end of jumbotron -->

{% endblock body %}

app/templates/signup.html
{%extends 'base.html'%}
{% load crispy_forms_tags%} <!-- crispy forms loaded-->
{% block title %}
	Signup
{% endblock title %}

{% block body %}

	<div class = "jumbotron">   <!-- jumbotron form container-->
	<form method = "POST" action = "{% url 'app:signup' %}" enctype="multipart/form-data">
	{%csrf_token%}
	{{form|crispy}}
	<input type="submit" value="Signup">
	</form>
	</div>  <!-- end of jumbotron -->

{% endblock body %}

app/templates/simple.html
{%extends "base.html"%}
{% block title %}
	Simple file
{% endblock title %}


{% block body %}
	<p> simple html file linked with simple_render view </p>	
{% endblock body %}

app/templates/simple_detail.html
{%extends "base.html"%}
{%block title%}Simple Detail {%endblock%}

{% block body %}
		<ul>
			<li>Name: {{store.name}}</li>
			<li>Location: {{store.location}}</li>
			<li>Description: {{store.description}}</li>
		</ul>
	
{% endblock body %}

app/templates/simple_list.html
{%extends "base.html"%}
{%block title%}Simple list {%endblock%}

{%block body%}

	{%for store in stores%}

		<ul>
			<li>Name:{{store.name}}</li>
			<li>Location: {{store.location}}</li>
		</ul>

		<br> 
	{% endfor %}
	
{%endblock%}

	

app/templates/simple_wc.html
{%extends "base.html"%}
{%block title%}Simple file with context{%endblock%}

{%block body%}
	{{msg}}
{%endblock%}

app/templates/update.html
{%extends "base.html"%}
{% load crispy_forms_tags%} <!-- crispy forms loaded--> 
{%block title%}Create Store {%endblock%}

{%block body%}

	<div class = "jumbotron">   <!-- jumbotron form container-->
		<form method = "POST" action = "{% url 'app:update' store.slug %}" enctype="multipart/form-data">
		{%csrf_token%}
		{{form|crispy}}
		<input type="submit" value="Update Store">
		</form>
	</div>                      <!-- end of jumbotron form -->

{%endblock%}